[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "walk"
version = "0.1.0"
description = "Simulation of Alex walking home"
authors = [{name = "Henny"}]
dependencies = []

[tool.setuptools]
packages = ["walk"]

